spring:
  application:    name: business-domain-biblioteca
  datasource:
    url: jdbc:mysql://localhost/sprang_2_libros
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate: debug
server:
  port: 8081
eureka:  client:    service-url:      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
# Admin configuration
management:  endpoints:    web:      exposure:        include:        - "*"
  
# Pendiente de añadir dependencias de swagger
# springdoc.swagger-ui.enabled=true